# Generated by Django 5.0.6 on 2024-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0002_alter_medicament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='category',
            field=models.TextField(),
        ),
    ]
